"""
Integration tests for orchestrator downstream dependency resolution.

These tests use mocked agents (no real LLM / Gemini API key required).
They exercise the full orchestrator loop: state seeding → process_request
→ assert state mutations and agent execution order.

Run with:
    python -m pytest tests/integration/test_orchestrator_downstream.py -v
or:
    python tests/integration/test_orchestrator_downstream.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.orchestrator.execution_plan import ExecutionPlan
from src.orchestrator.master_agent import MasterOrchestrator
from src.state.project_state import ArchitectureDefinition, ProjectState, Requirements
from src.state.state_manager import StateManager
from src.storage.memory_store import InMemoryPersistenceAdapter
from src.protocols.schemas import RequirementsState


# ---------------------------------------------------------------------------
# Fake agents
# ---------------------------------------------------------------------------

class FakeArchitectAgent:
    """Simulates project_architect: produces an architecture state_delta."""

    def __init__(self, tech_stack: dict | None = None):
        self._tech_stack = tech_stack or {"backend": "Python/FastAPI", "frontend": "React"}

    async def process(self, input_data: dict) -> dict:
        return {
            "state_delta": {
                "architecture": {
                    "tech_stack": self._tech_stack,
                    "tech_stack_rationale": "Generated by fake architect",
                    "data_schema": None,
                    "system_diagram": None,
                    "api_design": [],
                    "deployment_strategy": None,
                }
            },
            "summary": f"Architecture generated with stack: {self._tech_stack}",
        }


class FakeRequirementsCollector:
    def __init__(self, *, is_complete: bool = True, progress: float = 1.0):
        self._is_complete = is_complete
        self._progress = progress

    async def process_message(self, user_input, requirements_state, history):
        return {
            "response": "Requirements noted.",
            "requirements": RequirementsState(
                project_type="web app",
                target_users=["solo user"],
                key_features=["Login", "Dashboard"],
                technical_constraints=["Python"],
                business_goals=["Stay organized"],
                timeline="2 weeks",
                budget="$0",
                is_complete=self._is_complete,
                progress=self._progress,
            ),
        }


class FakeExecutionPlannerAgent:
    """Simulates execution_planner agent: records that it was called."""

    def __init__(self):
        self.call_count = 0
        self.last_input = None

    async def process(self, input_data: dict) -> dict:
        self.call_count += 1
        self.last_input = input_data
        return {
            "state_delta": {},
            "summary": "Execution plan generated.",
        }


class ExplodingArchitectAgent:
    async def process(self, input_data: dict) -> dict:
        raise RuntimeError("architect boom")


class SlowArchitectAgent:
    async def process(self, input_data: dict) -> dict:
        await asyncio.sleep(0.05)
        return {"state_delta": {}, "summary": "Too slow"}


class CapturingRegistry:
    """Registry that tracks which agents were instantiated/called."""

    def __init__(self, agents: dict):
        self._agents = agents  # agent_id -> agent instance
        self.called: list[str] = []

    def get_agent(self, agent_id: str):
        agent = self._agents.get(agent_id)
        if agent is not None:
            self.called.append(agent_id)
        return agent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_orchestrator(state_manager, project_state, registry, plan):
    """Build an orchestrator with _graph.ainvoke patched to return a fixed plan."""
    orch = MasterOrchestrator.__new__(MasterOrchestrator)
    orch.state = state_manager
    orch.registry = registry

    mock_graph = MagicMock()
    mock_graph.ainvoke = AsyncMock(return_value={
        "project_state": project_state,
        "plan": plan,
        "intent": {"primary_intent": "architecture_design", "requires_agents": ["project_architect"], "confidence": 0.9},
        "error": None,
    })
    orch._graph = mock_graph
    return orch


def _plan_with_agents(*agent_ids: str) -> ExecutionPlan:
    from src.orchestrator.agent_store import get_agent_by_id
    plan = ExecutionPlan()
    for aid in agent_ids:
        entry = get_agent_by_id(aid)
        plan.add_task(agent_id=aid, required_context=(entry or {}).get("requires") or [])
    return plan


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_auto_mode_stops_after_architect_checkpoint():
    """Auto mode should execute only project_architect and expose execution_planner as the next step."""
    session_id = "test-35-downstream"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Login", "Dashboard"], constraints=["Python"]),
    )
    await persistence.save(session_id, seed.model_dump())

    fake_exec_planner = FakeExecutionPlannerAgent()
    registry = CapturingRegistry({
        "project_architect": FakeArchitectAgent(),
        "execution_planner": fake_exec_planner,
    })

    # Plan includes both agents (as downstream resolution would produce)
    plan = _plan_with_agents("project_architect", "execution_planner")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("Design the architecture", session_id)

    assert "project_architect" in registry.called, "project_architect should have been fetched"
    result_ids = [ar["agent_id"] for ar in response["agent_results"]]
    assert result_ids == ["project_architect"]
    assert "execution_planner" not in registry.called
    assert response["current_step"]["agent_id"] == "project_architect"
    assert response["next_step"]["agent_id"] == "execution_planner"
    assert response["awaiting_user_action"] is True

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "architecture_complete"
    assert state_dict["awaiting_user_action"] is True
    assert state_dict["next_recommended_agent_id"] == "execution_planner"
    print("  PASS: auto mode stops after architect and exposes execution_planner as the next step")


@pytest.mark.asyncio
async def test_requirements_completion_checkpoints_to_architect():
    """A completed requirements turn should checkpoint into project_architect."""
    session_id = "test-35-req-checkpoint"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(session_id=session_id, current_phase="initialization", requirements=Requirements())
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({"requirements_collector": FakeRequirementsCollector(is_complete=True, progress=1.0)})
    plan = _plan_with_agents("requirements_collector")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("I need a task app", session_id)

    assert [ar["agent_id"] for ar in response["agent_results"]] == ["requirements_collector"]
    assert response["current_step"]["agent_id"] == "requirements_collector"
    assert response["next_step"]["agent_id"] == "project_architect"
    assert response["awaiting_user_action"] is True

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "requirements_complete"
    assert state_dict["awaiting_user_action"] is True
    assert state_dict["next_recommended_agent_id"] == "project_architect"
    print("  PASS: requirements completion checkpoints into project_architect")


@pytest.mark.asyncio
async def test_incomplete_requirements_does_not_checkpoint_to_architect():
    """An incomplete requirements turn should remain in requirements gathering."""
    session_id = "test-35-req-incomplete"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(session_id=session_id, current_phase="initialization", requirements=Requirements())
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({"requirements_collector": FakeRequirementsCollector(is_complete=False, progress=0.6)})
    plan = _plan_with_agents("requirements_collector")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("I need a task app", session_id)

    assert [ar["agent_id"] for ar in response["agent_results"]] == ["requirements_collector"]
    assert response["current_step"]["agent_id"] == "requirements_collector"
    assert response["next_step"] is None
    assert response["awaiting_user_action"] is False

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "initialization"
    assert state_dict["requirements"]["is_complete"] is False
    assert state_dict["awaiting_user_action"] is False
    assert state_dict["next_recommended_agent_id"] is None
    print("  PASS: incomplete requirements do not checkpoint into project_architect")


@pytest.mark.asyncio
async def test_phase_transitions_after_architect():
    """
    3.5 + 3.2: after project_architect runs, current_phase becomes architecture_complete.
    """
    session_id = "test-35-phase"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Auth"]),
    )
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({"project_architect": FakeArchitectAgent()})
    plan = _plan_with_agents("project_architect")
    orch = _make_orchestrator(sm, seed, registry, plan)

    await orch.process_request("Generate architecture", session_id)

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "architecture_complete", \
        f"Expected architecture_complete, got {state_dict['current_phase']}"
    print("  PASS: phase transition → architecture_complete after project_architect")


@pytest.mark.asyncio
async def test_explicit_continue_runs_execution_planner_only():
    """
    After architect completes and checkpoints the flow, an explicit continue
    should run execution_planner only.
    """
    session_id = "test-35-change"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="architecture_complete",
        requirements=Requirements(functional=["Login"], constraints=["Node.js"]),
        architecture=ArchitectureDefinition(tech_stack={"backend": "Node.js/Express"}),
        awaiting_user_action=True,
        last_completed_agent_id="project_architect",
        next_recommended_agent_id="execution_planner",
        last_auto_plan_agent_ids=["project_architect", "execution_planner"],
    )
    await persistence.save(session_id, seed.model_dump())

    fake_exec_planner = FakeExecutionPlannerAgent()
    registry = CapturingRegistry({
        "execution_planner": fake_exec_planner,
    })

    plan = _plan_with_agents("project_architect", "execution_planner")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("continue", session_id)

    assert "execution_planner" in registry.called
    assert "project_architect" not in registry.called
    assert [ar["agent_id"] for ar in response["agent_results"]] == ["execution_planner"]
    assert response["current_step"]["agent_id"] == "execution_planner"
    assert response["next_step"]["agent_id"] == "mockup_agent"
    assert response["awaiting_user_action"] is True

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "planning_complete"
    assert state_dict["last_completed_agent_id"] == "execution_planner"
    assert state_dict["next_recommended_agent_id"] == "mockup_agent"
    print("  PASS: explicit continue runs execution_planner only")


@pytest.mark.asyncio
async def test_explicit_continue_after_requirements_runs_architect_only():
    """After the requirements checkpoint, explicit continue should run project_architect only."""
    session_id = "test-35-req-continue"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Login"], constraints=["Python"], is_complete=True, progress=1.0),
        awaiting_user_action=True,
        last_completed_agent_id="requirements_collector",
        next_recommended_agent_id="project_architect",
        last_auto_plan_agent_ids=["requirements_collector"],
    )
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({
        "project_architect": FakeArchitectAgent(),
        "execution_planner": FakeExecutionPlannerAgent(),
    })

    plan = _plan_with_agents("requirements_collector", "project_architect")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("continue", session_id)

    assert "project_architect" in registry.called
    assert "requirements_collector" not in registry.called
    assert [ar["agent_id"] for ar in response["agent_results"]] == ["project_architect"]
    assert response["current_step"]["agent_id"] == "project_architect"
    assert response["next_step"]["agent_id"] == "execution_planner"
    assert response["awaiting_user_action"] is True

    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "architecture_complete"
    assert state_dict["next_recommended_agent_id"] == "execution_planner"
    print("  PASS: explicit continue after requirements runs project_architect only")


@pytest.mark.asyncio
async def test_change_request_reruns_architect_only_and_preserves_checkpoint():
    """
    A change request after architecture should re-run project_architect only in auto mode.
    """
    session_id = "test-35-agent-results"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="architecture_complete",
        requirements=Requirements(functional=["Auth"]),
        architecture=ArchitectureDefinition(tech_stack={"backend": "Node.js/Express"}),
        awaiting_user_action=True,
        last_completed_agent_id="project_architect",
        next_recommended_agent_id="execution_planner",
        last_auto_plan_agent_ids=["project_architect", "execution_planner"],
    )
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({
        "project_architect": FakeArchitectAgent(tech_stack={"backend": "Python/FastAPI"}),
        "execution_planner": FakeExecutionPlannerAgent(),
    })

    plan = _plan_with_agents("project_architect", "execution_planner")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("Change backend to Python/FastAPI", session_id)

    agent_result_ids = [ar["agent_id"] for ar in response["agent_results"]]
    assert agent_result_ids == ["project_architect"]
    assert "execution_planner" not in registry.called
    state_dict = await persistence.get(session_id)
    assert state_dict["architecture"]["tech_stack"]["backend"] == "Python/FastAPI"
    assert state_dict["next_recommended_agent_id"] == "execution_planner"
    assert state_dict["awaiting_user_action"] is True
    print(f"  PASS: change request re-runs architect only: {agent_result_ids}")


@pytest.mark.asyncio
async def test_downstream_blocked_when_upstream_fails():
    """If architect fails in auto mode, the flow stops immediately and does not run execution_planner."""
    session_id = "test-35-blocked"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Auth"]),
    )
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({
        "project_architect": ExplodingArchitectAgent(),
        "execution_planner": FakeExecutionPlannerAgent(),
    })
    plan = _plan_with_agents("project_architect", "execution_planner")
    orch = _make_orchestrator(sm, seed, registry, plan)

    response = await orch.process_request("Design and plan", session_id)

    arch_result = next(ar for ar in response["agent_results"] if ar["agent_id"] == "project_architect")
    assert arch_result["status"] == "failed_runtime"
    assert len(response["agent_results"]) == 1
    assert "execution_planner" not in registry.called
    state_dict = await persistence.get(session_id)
    assert state_dict["current_phase"] == "requirements_complete"
    assert state_dict["awaiting_user_action"] is False
    print("  PASS: auto mode stops after upstream runtime failure")


@pytest.mark.asyncio
async def test_timeout_marks_agent_failed_timeout():
    """Orchestrator-level timeout should mark the agent as failed_timeout."""
    from src.orchestrator import master_agent as master_agent_module

    session_id = "test-35-timeout"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Auth"]),
    )
    await persistence.save(session_id, seed.model_dump())

    registry = CapturingRegistry({"project_architect": SlowArchitectAgent()})
    plan = _plan_with_agents("project_architect")
    orch = _make_orchestrator(sm, seed, registry, plan)

    original_timeout = master_agent_module.AGENT_TIMEOUT_SECONDS["project_architect"]
    master_agent_module.AGENT_TIMEOUT_SECONDS["project_architect"] = 0.01
    try:
        response = await orch.process_request("Generate architecture", session_id)
    finally:
        master_agent_module.AGENT_TIMEOUT_SECONDS["project_architect"] = original_timeout

    arch_result = next(ar for ar in response["agent_results"] if ar["agent_id"] == "project_architect")
    assert arch_result["status"] == "failed_timeout"
    assert "Timed out" in arch_result.get("error", "")
    print("  PASS: orchestrator timeout marks agent as failed_timeout")


@pytest.mark.asyncio
async def test_manual_mode_only_runs_selected_agent():
    """
    3.5 + 3.4 manual mode: only the selected agent (and its upstream) runs.
    Downstream agents are NOT appended in manual mode.
    """
    session_id = "test-35-manual"
    persistence = InMemoryPersistenceAdapter()
    sm = StateManager(persistence)

    seed = ProjectState(
        session_id=session_id,
        current_phase="requirements_complete",
        requirements=Requirements(functional=["Auth"]),
    )
    await persistence.save(session_id, seed.model_dump())

    fake_exec_planner = FakeExecutionPlannerAgent()
    registry = CapturingRegistry({
        "project_architect": FakeArchitectAgent(),
        "execution_planner": fake_exec_planner,
    })

    # In manual mode, _graph is never called — orchestrator builds plan itself
    orch = MasterOrchestrator.__new__(MasterOrchestrator)
    orch.state = sm
    orch.registry = registry
    mock_graph = MagicMock()
    mock_graph.ainvoke = AsyncMock(side_effect=AssertionError("graph should not be called in manual mode"))
    orch._graph = mock_graph

    response = await orch.process_request(
        "Run architect only",
        session_id,
        agent_selection_mode="manual",
        selected_agent_id="project_architect",
    )

    # Only project_architect should have run (execution_planner is downstream, not upstream)
    assert "project_architect" in registry.called
    assert "execution_planner" not in registry.called, \
        "execution_planner should NOT run in manual mode (downstream not expanded)"
    assert response["intent"]["primary_intent"] == "manual"
    print("  PASS: manual mode ran only project_architect, not downstream execution_planner")


# ---------------------------------------------------------------------------
# Standalone runner (no pytest needed)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    tests = [
        test_auto_mode_stops_after_architect_checkpoint,
        test_requirements_completion_checkpoints_to_architect,
        test_incomplete_requirements_does_not_checkpoint_to_architect,
        test_phase_transitions_after_architect,
        test_explicit_continue_runs_execution_planner_only,
        test_explicit_continue_after_requirements_runs_architect_only,
        test_change_request_reruns_architect_only_and_preserves_checkpoint,
        test_downstream_blocked_when_upstream_fails,
        test_timeout_marks_agent_failed_timeout,
        test_manual_mode_only_runs_selected_agent,
    ]

    async def run_all():
        print("\n=== Part 3.5 — Integration Tests (Change Request / Downstream) ===\n")
        passed = 0
        for test in tests:
            print(f"Running {test.__name__}...")
            try:
                await test()
                passed += 1
            except AssertionError as e:
                print(f"  FAIL: {e}")
            except Exception as e:
                import traceback
                print(f"  ERROR: {type(e).__name__}: {e}")
                traceback.print_exc()
        print(f"\n{'='*60}")
        print(f"Results: {passed}/{len(tests)} passed")
        if passed < len(tests):
            sys.exit(1)

    asyncio.run(run_all())
