import { ListChecks, GitPullRequest, ArrowRightCircle } from "lucide-react";

export default function ExecutionPanel() {
  return (
    <>
      <div className="h-10 border-b border-gray-300 dark:border-[#444] flex items-center justify-between px-4 bg-gray-50 dark:bg-black flex-shrink-0 transition-colors">
        <div className="flex items-center gap-2 text-black dark:text-white">
          <ListChecks size={12} />
          <span className="text-[10px] tracking-widest uppercase font-bold text-black dark:text-white">Execution_Plan</span>
        </div>
        <div className="flex gap-2">
           <span className="text-[9px] border border-gray-300 dark:border-[#555] bg-white dark:bg-[#111] px-2 py-1 text-gray-600 dark:text-gray-300 font-bold uppercase tracking-widest flex items-center gap-1 transition-colors">
             Target_Actor: Human_Operator
           </span>
        </div>
      </div>

      <div className="p-6 overflow-y-auto flex-1 bg-white dark:bg-black transition-colors">
        <div className="mb-8 pb-4 border-b border-gray-200 dark:border-[#333]">
          <h1 className="text-lg font-bold text-black dark:text-white mb-2 tracking-tight uppercase">Implementation Roadmap</h1>
          <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-mono">
            &gt; Generated by Execution_Planner_Agent. 
            <br />&gt; Please follow these sequential milestones to implement the approved architecture.
          </p>
        </div>

        <div className="mb-8">
          <h2 className="text-[10px] font-bold text-black dark:text-white tracking-widest uppercase mb-6 flex items-center gap-2">
            <ArrowRightCircle size={14} className="text-gray-400 dark:text-gray-500" />
            Milestone Tracking
          </h2>
          
          <div className="space-y-8 relative border-l border-gray-200 dark:border-[#444] ml-2 pl-6 transition-colors">
            
            <div className="relative">
              <div className="absolute -left-[29px] top-0 w-3 h-3 bg-white dark:bg-black rounded-full border-2 border-black dark:border-white transition-colors"></div>
              <h3 className="text-xs font-bold text-black dark:text-white uppercase tracking-widest mb-1 flex items-center gap-2">
                Phase 1: Foundation & Setup
              </h3>
              <p className="text-[10px] text-gray-500 mb-3 font-bold">ESTIMATED EFFORT: 2 HOURS</p>
              <ul className="space-y-3">
                <li className="text-sm text-gray-700 dark:text-gray-200 flex items-start gap-3 bg-gray-50 dark:bg-[#050505] p-3 border border-gray-200 dark:border-[#333] transition-colors">
                  <span className="text-gray-400 dark:text-gray-500 mt-0.5">[ ]</span> 
                  <div>
                    <span className="font-bold text-black dark:text-white block mb-1">Initialize repository and CI/CD</span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">Set up Next.js frontend and FastAPI backend environments. Configure GitHub Actions for linting.</span>
                  </div>
                </li>
                <li className="text-sm text-gray-700 dark:text-gray-200 flex items-start gap-3 bg-gray-50 dark:bg-[#050505] p-3 border border-gray-200 dark:border-[#333] transition-colors">
                  <span className="text-gray-400 dark:text-gray-500 mt-0.5">[ ]</span> 
                  <div>
                    <span className="font-bold text-black dark:text-white block mb-1">Define base database schemas</span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">Execute the Prisma schema generated by the Project Architect in milestone 0.</span>
                  </div>
                </li>
              </ul>
            </div>

            <div className="relative">
              <div className="absolute -left-[29px] top-0 w-3 h-3 bg-white dark:bg-black rounded-full border-2 border-gray-400 dark:border-[#555] transition-colors"></div>
              <h3 className="text-xs font-bold text-black dark:text-white uppercase tracking-widest mb-1 flex items-center gap-2">
                Phase 2: Core Routing & Auth
              </h3>
              <p className="text-[10px] text-gray-500 mb-3 font-bold">ESTIMATED EFFORT: 4 HOURS</p>
              <ul className="space-y-3">
                <li className="text-sm text-gray-700 dark:text-gray-200 flex items-start gap-3 bg-gray-50 dark:bg-[#050505] p-3 border border-gray-200 dark:border-[#333] transition-colors">
                  <span className="text-gray-400 dark:text-gray-500 mt-0.5">[ ]</span> 
                  <div className="w-full">
                    <span className="font-bold text-black dark:text-white block mb-1">Implement Authentication Gateway</span>
                    <span className="text-xs text-gray-500 dark:text-gray-400 block mb-2">Build the OAuth handshake and session cookie logic in middleware.ts.</span>
                    <div className="flex gap-2">
                      <span className="text-[9px] border border-gray-300 dark:border-[#444] bg-white dark:bg-transparent px-1.5 py-0.5 text-gray-500 dark:text-gray-400 flex items-center gap-1 transition-colors">
                        <GitPullRequest size={10} /> DEPENDS_ON: PHASE_01
                      </span>
                    </div>
                  </div>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </>
  );
}