"use client";
import { ListChecks, GitPullRequest, ArrowRightCircle } from "lucide-react";
import { useProjectStore } from "@/store/useProjectStore";

export default function ExecutionPanel() {
  const { roadmap, isLoading } = useProjectStore();

  const phases: any[] = roadmap?.phases ?? [];
  const milestones: any[] = roadmap?.milestones ?? [];
  const tasks: any[] = roadmap?.implementation_tasks ?? [];
  const hasData = !!(phases.length || milestones.length || tasks.length);

  // Group tasks by phase_name for display
  const tasksByPhase: Record<string, any[]> = {};
  for (const task of tasks) {
    const phase = task.phase_name ?? "General";
    if (!tasksByPhase[phase]) tasksByPhase[phase] = [];
    tasksByPhase[phase].push(task);
  }

  const phaseNames = phases.length
    ? phases.sort((a, b) => (a.order ?? 0) - (b.order ?? 0)).map((p) => p.name)
    : Object.keys(tasksByPhase);

  return (
    <>
      <div className="h-10 border-b border-gray-300 dark:border-[#444] flex items-center justify-between px-4 bg-gray-50 dark:bg-black flex-shrink-0 transition-colors">
        <div className="flex items-center gap-2 text-black dark:text-white">
          <ListChecks size={12} />
          <span className="text-[10px] tracking-widest uppercase font-bold text-black dark:text-white">Execution_Plan</span>
        </div>
        {hasData && (
          <span className="text-[9px] border border-gray-300 dark:border-[#555] bg-white dark:bg-[#111] px-2 py-1 text-gray-600 dark:text-gray-300 font-bold uppercase tracking-widest transition-colors">
            {tasks.length} Tasks · {phases.length || phaseNames.length} Phases
          </span>
        )}
      </div>

      <div className="p-6 overflow-y-auto flex-1 bg-white dark:bg-black transition-colors">
        {isLoading && !hasData && (
          <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest animate-pulse">
            -- LOADING EXECUTION PLAN --
          </p>
        )}

        {!isLoading && !hasData && (
          <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">
            -- NO EXECUTION PLAN YET. RUN THE EXECUTION PLANNER AGENT FROM THE CONSOLE --
          </p>
        )}

        {hasData && (
          <>
            <div className="mb-8 pb-4 border-b border-gray-200 dark:border-[#333]">
              <h1 className="text-lg font-bold text-black dark:text-white mb-2 tracking-tight uppercase">Implementation Roadmap</h1>
              <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-mono">
                &gt; Generated by Execution_Planner_Agent.
              </p>
            </div>

            <div className="mb-8">
              <h2 className="text-[10px] font-bold text-black dark:text-white tracking-widest uppercase mb-6 flex items-center gap-2">
                <ArrowRightCircle size={14} className="text-gray-400 dark:text-gray-500" />
                Milestone Tracking
              </h2>

              <div className="space-y-8 relative border-l border-gray-200 dark:border-[#444] ml-2 pl-6 transition-colors">
                {phaseNames.map((phaseName, pi) => {
                  const phaseTasks = tasksByPhase[phaseName] ?? [];
                  const phaseObj = phases.find((p) => p.name === phaseName);
                  return (
                    <div key={pi} className="relative">
                      <div className="absolute -left-[29px] top-0 w-3 h-3 bg-white dark:bg-black rounded-full border-2 border-black dark:border-white transition-colors" />
                      <h3 className="text-xs font-bold text-black dark:text-white uppercase tracking-widest mb-1">
                        Phase {pi + 1}: {phaseName}
                      </h3>
                      {phaseObj?.description && (
                        <p className="text-[10px] text-gray-500 mb-3 font-mono">{phaseObj.description}</p>
                      )}
                      {phaseTasks.length > 0 && (
                        <ul className="space-y-3">
                          {phaseTasks
                            .sort((a, b) => (a.order ?? 0) - (b.order ?? 0))
                            .map((task: any, ti: number) => (
                              <li key={ti} className="text-sm text-gray-700 dark:text-gray-200 flex items-start gap-3 bg-gray-50 dark:bg-[#050505] p-3 border border-gray-200 dark:border-[#333] transition-colors">
                                <span className="text-gray-400 dark:text-gray-500 mt-0.5 shrink-0">[ ]</span>
                                <div className="w-full">
                                  <span className="font-bold text-black dark:text-white block mb-1">{task.title}</span>
                                  {task.description && (
                                    <span className="text-xs text-gray-500 dark:text-gray-400 block mb-2">{task.description}</span>
                                  )}
                                  {task.depends_on?.length > 0 && (
                                    <div className="flex gap-2 flex-wrap">
                                      {task.depends_on.map((dep: string) => (
                                        <span key={dep} className="text-[9px] border border-gray-300 dark:border-[#444] bg-white dark:bg-transparent px-1.5 py-0.5 text-gray-500 dark:text-gray-400 flex items-center gap-1 transition-colors">
                                          <GitPullRequest size={10} /> DEPENDS: {dep}
                                        </span>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              </li>
                            ))}
                        </ul>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
}