import { FileText, CheckCircle2 } from "lucide-react";

export default function RequirementPanel() {
  return (
    <>
      <div className="h-10 border-b border-gray-300 dark:border-[#444] flex items-center justify-between px-4 bg-gray-50 dark:bg-black flex-shrink-0 transition-colors">
        <div className="flex items-center gap-2 text-black dark:text-white">
          <FileText size={12} />
          <span className="text-[10px] tracking-widest uppercase font-bold">Project_Requirements</span>
        </div>
        <div className="flex gap-2">
           <span className="text-[9px] border border-blue-200 dark:border-blue-900/50 bg-blue-50 dark:bg-blue-900/20 px-2 py-1 text-blue-700 dark:text-blue-400 font-bold uppercase tracking-widest flex items-center gap-1">
             Status: Collected
           </span>
        </div>
      </div>

      <div className="p-6 overflow-y-auto flex-1 bg-white dark:bg-black transition-colors">
        <div className="mb-8 pb-4 border-b border-gray-200 dark:border-[#333]">
          <h1 className="text-lg font-bold text-black dark:text-white mb-2 tracking-tight uppercase">Raw Requirement Extraction</h1>
          <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-mono">
            &gt; Generated by Requirements_Collector_Agent. 
            <br />&gt; Synthesized from user interview chat log. Ready for Project Architect review.
          </p>
        </div>

        <div className="space-y-6">
          <div className="border border-gray-200 dark:border-[#333] bg-gray-50 dark:bg-[#050505] p-4 transition-colors">
            <h3 className="text-xs font-bold text-black dark:text-white uppercase tracking-widest mb-3 border-b border-gray-200 dark:border-[#333] pb-2 flex items-center gap-2">
              <CheckCircle2 size={14} className="text-green-600 dark:text-green-500" />
              Core Objectives
            </h3>
            <ul className="space-y-2 font-mono text-sm text-gray-700 dark:text-gray-300">
              <li className="flex gap-3"><span className="text-gray-400 dark:text-gray-600">01</span>Build an AI-driven multi-agent planning system.</li>
              <li className="flex gap-3"><span className="text-gray-400 dark:text-gray-600">02</span>Transform short project ideas into structured project plans.</li>
              <li className="flex gap-3"><span className="text-gray-400 dark:text-gray-600">03</span>Export deliverables to Markdown, PDF, or GitHub README.</li>
            </ul>
          </div>

          <div className="border border-gray-200 dark:border-[#333] bg-gray-50 dark:bg-[#050505] p-4 transition-colors">
            <h3 className="text-xs font-bold text-black dark:text-white uppercase tracking-widest mb-3 border-b border-gray-200 dark:border-[#333] pb-2 flex items-center gap-2">
              <CheckCircle2 size={14} className="text-green-600 dark:text-green-500" />
              Agent Roster
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="bg-white dark:bg-black border border-gray-200 dark:border-[#444] p-3">
                <span className="text-[10px] font-bold text-purple-600 dark:text-purple-400 uppercase block mb-1">Requirements Collector</span>
                <span className="text-xs text-gray-600 dark:text-gray-400">Interviews user, gathers constraints.</span>
              </div>
              <div className="bg-white dark:bg-black border border-gray-200 dark:border-[#444] p-3">
                <span className="text-[10px] font-bold text-blue-600 dark:text-blue-400 uppercase block mb-1">Project Architect</span>
                <span className="text-xs text-gray-600 dark:text-gray-400">Converts requirements to system design.</span>
              </div>
              <div className="bg-white dark:bg-black border border-gray-200 dark:border-[#444] p-3">
                <span className="text-[10px] font-bold text-red-600 dark:text-red-400 uppercase block mb-1">Execution Planner</span>
                <span className="text-xs text-gray-600 dark:text-gray-400">Generates implementation milestones.</span>
              </div>
              <div className="bg-white dark:bg-black border border-gray-200 dark:border-[#444] p-3">
                <span className="text-[10px] font-bold text-green-600 dark:text-green-400 uppercase block mb-1">Exporter Agent</span>
                <span className="text-xs text-gray-600 dark:text-gray-400">Organizes final plan into deliverables.</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}